'use client';
import {useState,useEffect,useRef} from 'react';
import {ArrowDown,ArrowUpRight,ArrowRight,ArrowLeft,ArrowDownRight,Menu,X,Plus,Minus,Instagram} from 'lucide-react';
import {AnimatePresence,motion,useReducedMotion} from 'framer-motion';

const photos=(...nums:number[])=>nums.map(n=>`/images/interior-${String(n).padStart(2,'0')}.jpg`);
const projects=[
 {title:'Spaces for living',type:'Residential interior',year:'2026',cover:photos(22)[0],images:photos(22,9,6,12,18),number:'01'},
 {title:'The quieter rooms',type:'Private residence',year:'2026',cover:photos(15)[0],images:photos(15,24,3,10,13),number:'02'},
 {title:'Light in the everyday',type:'Kitchen & living',year:'2025',cover:photos(17)[0],images:photos(17,19,20,16,4),number:'03'},
 {title:'A considered interior',type:'Spatial design',year:'2025',cover:photos(2)[0],images:photos(2,7,8,11,14),number:'04'}
];
const ease=[0.22,1,0.36,1] as const;
export default function Home(){
 const [active,setActive]=useState(0),[changing,setChanging]=useState(false),[menu,setMenu]=useState(false),[detail,setDetail]=useState<number|null>(null),[expanded,setExpanded]=useState<number|null>(null);
 const prefersReduced=useReducedMotion(); const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 function navigate(n:number){if(changing)return;setChanging(true);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{setActive((n+projects.length)%projects.length);setChanging(false)},prefersReduced?0:380)}
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 useEffect(()=>{document.body.style.overflow=detail!==null||menu?'hidden':'';return ()=>{document.body.style.overflow=''}},[detail,menu]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){setDetail(null);setMenu(false)}if(detail===null&&!menu&&(e.key==='ArrowRight'||e.key==='ArrowLeft'))navigate(active+(e.key==='ArrowRight'?1:-1))};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[active,detail,menu,changing]);
 const project=projects[active];
 return <main>
 <header className="header"><a href="#home" className="wordmark" onClick={()=>setMenu(false)}>FO<span>R</span>MA<span className="wordmark-dot">.</span><small>INTERIOR STUDIO / CONCEPT</small></a><nav className="desktop-nav"><a href="#studio">Studio</a><a href="#projects">Projects</a><a href="#approach">Approach</a><a href="#contact">Contact</a></nav><button className="menu-button" aria-label={menu?'Close menu':'Open menu'} onClick={()=>setMenu(v=>!v)}>{menu?<X size={24}/>:<><span>MENU</span><Menu size={21}/></>}</button></header>
 <AnimatePresence>{menu&&<motion.div className="mobile-menu" initial={{opacity:0,y:-20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-20}} transition={{duration:.3}}>{[['Studio','#studio'],['Projects','#projects'],['Approach','#approach'],['Contact','#contact']].map(([name,url],i)=><a href={url} key={name} onClick={()=>setMenu(false)}><span>0{i+1}</span>{name}<ArrowUpRight size={22}/></a>)}<p>FORMA — AN INTERIOR DESIGN WEBSITE CONCEPT</p></motion.div>}</AnimatePresence>
 <section id="home" className="hero" aria-label="Featured projects"><div className="hero-images">{projects.map((p,i)=><div className={`hero-image ${active===i?'is-active':''}`} key={p.title} style={{backgroundImage:`url('${p.cover}')`}}/>)}<div className="hero-shade"/></div>
 <div className="hero-main" key={active}><div className="hero-year"><span className="small-label">FEATURED WORK / {project.number}—04</span><span>{project.year}</span></div><div className="hero-title"><span className="hero-title-arc">(</span><div><span className="eyebrow">SELECTED INTERIORS</span><h1>{project.title}</h1></div><span className="hero-title-arc">)</span></div><button className="hero-view" onClick={()=>setDetail(active)}>Explore project <ArrowUpRight size={20}/></button></div>
 <div className="hero-bottom"><p>Spaces shaped by the way<br/>we move, gather and live.</p><div className="hero-navigation"><button onClick={()=>navigate(active-1)} aria-label="Previous project"><ArrowLeft size={20}/></button><span className="fraction">0{active+1} <i/> 0{projects.length}</span><button onClick={()=>navigate(active+1)} aria-label="Next project"><ArrowRight size={20}/></button></div><button className="next-button" onClick={()=>navigate(active+1)}>Next project <ArrowDown size={21}/></button></div><a href="#studio" className="scroll-cue">SCROLL TO EXPLORE <ArrowDown size={15}/></a>
 <div className={`scene-wipe ${changing?'is-wiping':''}`}/>
 </section>
 <section id="studio" className="intro section-pad"><div className="section-kicker"><span>01 / THE STUDIO</span><span>AN INTRODUCTION</span></div><div className="intro-grid"><div className="intro-small"><span className="star">✳</span><span>DESIGN BEGINS<br/>WITH ATTENTION.</span></div><div><h2>Interiors are not simply <em>seen.</em> They are <em>felt.</em></h2><div className="intro-lower"><p>We believe that meaningful spaces emerge from the conversation between architecture, material, light and the people who inhabit them.</p><a className="line-link" href="#approach">Discover our approach <ArrowUpRight size={20}/></a></div></div></div></section>
 <section id="projects" className="work section-pad"><div className="section-kicker"><span>02 / SELECTED SPACES</span><span>(04 PROJECT STUDIES)</span></div><div className="work-heading"><h2>Rooms to <em>remember.</em></h2><p>AN EXPLORATION OF MATERIAL,<br/>PROPORTION AND ATMOSPHERE.</p></div><div className="project-grid">{projects.map((p,i)=><button className={`project-card project-card-${i+1}`} key={p.title} onClick={()=>setDetail(i)}><span className="project-image-wrap"><img src={p.cover} alt={p.type} loading="lazy"/><span className="project-open"><ArrowUpRight size={25}/></span></span><span className="project-meta"><span><b>{p.title}</b><small>{p.type}</small></span><span>{p.number} / {p.year}</span></span></button>)}</div></section>
 <section className="manifesto"><div className="manifesto-img"/><div className="manifesto-overlay"/><div className="manifesto-content"><div className="section-kicker"><span>AN ONGOING STUDY</span><span>FORM / FUNCTION / FEELING</span></div><span className="manifesto-number">/ 003</span><h2>Not just<br/><em>a place.</em><br/>A feeling.</h2><p>Every detail changes the way a space is experienced.</p></div></section>
 <section id="approach" className="approach section-pad"><div className="section-kicker"><span>03 / OUR APPROACH</span><span>THE THOUGHT BEHIND THE SPACE</span></div><div className="approach-head"><h2>Thoughtfully made.<br/><em>Quietly lived in.</em></h2><p>From first conversation to the final detail, each space is shaped with care and purpose.</p></div><div className="approach-list">{[{n:'01',title:'Listen',body:'Every project begins by understanding daily rituals, aspirations, constraints and the small things that make a space feel like home.'},{n:'02',title:'Imagine',body:'Ideas take shape through spatial planning, material explorations, lighting, and thoughtful design decisions.'},{n:'03',title:'Refine',body:'Proportion, craftsmanship, and detail come together to create an atmosphere that lasts beyond the moment.'}].map((a,i)=><div className="approach-item" key={a.n}><button onClick={()=>setExpanded(expanded===i?null:i)} aria-expanded={expanded===i}><span>{a.n}</span><strong>{a.title}</strong>{expanded===i?<Minus size={24}/>:<Plus size={24}/>}</button><AnimatePresence>{expanded===i&&<motion.p initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={{duration:.3}}>{a.body}</motion.p>}</AnimatePresence></div>)}</div></section>
 <section id="contact" className="contact section-pad"><div className="section-kicker"><span>04 / GET IN TOUCH</span><span>THE NEXT CHAPTER</span></div><span className="contact-star">✳</span><p>HAVE A SPACE IN MIND?</p><h2>Let's make room<br/>for <em>something new.</em></h2><a href="mailto:hello@example.com?subject=Interior%20project%20enquiry" className="contact-cta" title="Replace the sample email with the studio's real contact email">Start a conversation <ArrowUpRight size={27}/></a><div className="footer"><span>FORMA<span className="wordmark-dot">.</span> <small>© {new Date().getFullYear()}</small></span><span>CONCEPT WEBSITE · STUDIO DETAILS TO BE CONFIRMED</span><a href="#home">BACK TO TOP ↑</a></div></section>
 <AnimatePresence>{detail!==null&&<motion.div className="detail" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.3}} role="dialog" aria-modal="true" aria-label={projects[detail].title}><button className="detail-close" onClick={()=>setDetail(null)}><X size={22}/> CLOSE</button><div className="detail-hero" style={{backgroundImage:`linear-gradient(0deg,rgba(0,0,0,.5),rgba(0,0,0,.1)),url('${projects[detail].cover}')`}}><div><span>PROJECT STUDY / {projects[detail].number}</span><h2>{projects[detail].title}</h2><p>{projects[detail].type} · {projects[detail].year}</p></div></div><div className="detail-body"><div className="detail-note"><span>THE SPACE</span><p>A visual study of considered interiors, material, natural light and the details that create atmosphere.</p><small>Project names and descriptions are concept placeholders, pending studio confirmation.</small></div><div className="detail-gallery">{projects[detail].images.slice(1).map((img,i)=><img key={img} src={img} alt={`${projects[detail].title} interior detail ${i+1}`} loading="lazy"/>)}</div><div className="detail-end"><button onClick={()=>setDetail((detail+1)%projects.length)}>Next project <ArrowUpRight size={23}/></button><button onClick={()=>setDetail(null)}>Back to site <X size={19}/></button></div></div></motion.div>}</AnimatePresence>
 </main>}
