'use client';
import {useState,useEffect,useRef} from 'react';
import {ArrowDown,ArrowUpRight,ArrowRight,ArrowLeft,ArrowDownRight,Menu,X,Instagram,Orbit,Layers3,ScanLine,PanelsTopLeft} from 'lucide-react';
import {AnimatePresence,motion,useReducedMotion,useScroll,useTransform,useMotionValueEvent} from 'framer-motion';

const photos=(...nums:number[])=>nums.map(n=>`/images/interior-${String(n).padStart(2,'0')}.jpg`);
const projects=[
 {title:'Spaces for living',type:'Residential interior',year:'2026',cover:photos(22)[0],images:photos(22,9,6,12,18),number:'01'},
 {title:'The quieter rooms',type:'Private residence',year:'2026',cover:photos(15)[0],images:photos(15,24,3,10,13),number:'02'},
 {title:'Light in the everyday',type:'Kitchen & living',year:'2025',cover:photos(17)[0],images:photos(17,19,20,16,4),number:'03'},
 {title:'A considered interior',type:'Spatial design',year:'2025',cover:photos(2)[0],images:photos(2,7,8,11,14),number:'04'}
];
const ease=[0.22,1,0.36,1] as const;
export default function Home(){
 const [enquiryOpen,setEnquiryOpen]=useState(false),[enquiry,setEnquiry]=useState({type:'Residential interior',location:'',name:'',email:'',details:''}); const [active,setActive]=useState(0),[changing,setChanging]=useState(false),[menu,setMenu]=useState(false),[detail,setDetail]=useState<number|null>(null);
 const introRef=useRef<HTMLElement|null>(null); const approachRef=useRef<HTMLElement|null>(null); const approachTrack=useRef<HTMLDivElement|null>(null); const prefersReduced=useReducedMotion(); const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 function navigate(n:number){if(changing)return;setChanging(true);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{setActive((n+projects.length)%projects.length);setChanging(false)},prefersReduced?0:380)}
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 useEffect(()=>{document.body.style.overflow=detail!==null||menu||enquiryOpen?'hidden':'';return ()=>{document.body.style.overflow=''}},[detail,menu,enquiryOpen]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){setDetail(null);setMenu(false);setEnquiryOpen(false)}if(detail===null&&!menu&&(e.key==='ArrowRight'||e.key==='ArrowLeft'))navigate(active+(e.key==='ArrowRight'?1:-1))};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[active,detail,menu,changing]);
 const {scrollYProgress:introProgress}=useScroll({target:introRef,offset:['start end','end start']});
 const introFloatA=useTransform(introProgress,[0,1],[180,-180]);
 const introFloatB=useTransform(introProgress,[0,1],[270,-220]);
 const introFloatC=useTransform(introProgress,[0,1],[140,-280]);
 const introFloatD=useTransform(introProgress,[0,1],[240,-160]);
 const introTypeY=useTransform(introProgress,[0.2,0.6],[50,-20]);
 const {scrollYProgress:approachProgress}=useScroll({target:approachRef,offset:['start start','end end']});
 useMotionValueEvent(approachProgress,'change',progress=>{
  if(typeof window==='undefined'||window.matchMedia('(max-width: 700px), (prefers-reduced-motion: reduce)').matches)return;
  const track=approachTrack.current;
  if(track)track.scrollLeft=progress*(track.scrollWidth-track.clientWidth);
 });
 const project=projects[active];
 return <main>
 <header className="header"><a href="#home" className="wordmark" onClick={()=>setMenu(false)}>FO<span>R</span>MA<span className="wordmark-dot">.</span><small>INTERIOR STUDIO / CONCEPT</small></a><nav className="desktop-nav"><a href="#studio">Studio</a><a href="#projects">Projects</a><a href="#approach">Approach</a><a href="#contact">Contact</a></nav><button className="menu-button" aria-label={menu?'Close menu':'Open menu'} onClick={()=>setMenu(v=>!v)}>{menu?<X size={24}/>:<><span>MENU</span><Menu size={21}/></>}</button></header>
 <AnimatePresence>{menu&&<motion.div className="mobile-menu" initial={{opacity:0,y:-20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-20}} transition={{duration:.3}}>{[['Studio','#studio'],['Projects','#projects'],['Approach','#approach'],['Contact','#contact']].map(([name,url],i)=><a href={url} key={name} onClick={()=>setMenu(false)}><span>0{i+1}</span>{name}<ArrowUpRight size={22}/></a>)}<p>FORMA — AN INTERIOR DESIGN WEBSITE CONCEPT</p></motion.div>}</AnimatePresence>
 <section id="home" className="hero" aria-label="Featured projects"><div className="hero-images">{projects.map((p,i)=><div className={`hero-image ${active===i?'is-active':''}`} key={p.title} style={{backgroundImage:`url('${p.cover}')`}}/>)}<div className="hero-shade"/></div>
 <div className="hero-main" key={active}><div className="hero-year"><span className="small-label">FEATURED WORK / {project.number}—04</span><span>{project.year}</span></div><div className="hero-title"><span className="hero-title-arc">(</span><div><span className="eyebrow">SELECTED INTERIORS</span><h1>{project.title}</h1></div><span className="hero-title-arc">)</span></div><button className="hero-view" onClick={()=>setDetail(active)}>Explore project <ArrowUpRight size={20}/></button></div>
 <div className="hero-bottom"><p>Spaces shaped by the way<br/>we move, gather and live.</p><div className="hero-navigation"><button onClick={()=>navigate(active-1)} aria-label="Previous project"><ArrowLeft size={20}/></button><span className="fraction">0{active+1} <i/> 0{projects.length}</span><button onClick={()=>navigate(active+1)} aria-label="Next project"><ArrowRight size={20}/></button></div><button className="next-button" onClick={()=>navigate(active+1)}>Next project <ArrowDown size={21}/></button></div><a href="#studio" className="scroll-cue">SCROLL TO EXPLORE <ArrowDown size={15}/></a>
 <div className={`scene-wipe ${changing?'is-wiping':''}`}/>
 </section>
 <section id="studio" ref={introRef} className="intro-story"><div className="intro-sticky"><div className="intro-story-kicker"><span>01 / THE STUDIO</span><span>THE ART OF MAKING SPACE</span></div>
 <motion.div className="intro-center" style={{y:prefersReduced?0:introTypeY}}><span className="intro-center-label">[ A STUDY IN ATMOSPHERE ]</span><h2>Interiors are<br/>not simply <em>seen.</em><br/>They are <em>felt.</em></h2><span className="intro-center-arrow">↓</span></motion.div>
 <motion.figure className="intro-fragment intro-fragment-a" style={{y:prefersReduced?0:introFloatA}}><img src="/images/interior-09.jpg" loading="lazy" alt="Soft daylight across a considered living space"/><figcaption>01 — LIGHT</figcaption></motion.figure>
 <motion.figure className="intro-fragment intro-fragment-b" style={{y:prefersReduced?0:introFloatB}}><img src="/images/interior-03.jpg" loading="lazy" alt="Architectural interior and material detail"/><figcaption>02 — MATERIAL</figcaption></motion.figure>
 <motion.figure className="intro-fragment intro-fragment-c" style={{y:prefersReduced?0:introFloatC}}><img src="/images/interior-22.jpg" loading="lazy" alt="Contemporary living room with layered furnishings"/><figcaption>03 — FORM</figcaption></motion.figure>
 <motion.figure className="intro-fragment intro-fragment-d" style={{y:prefersReduced?0:introFloatD}}><img src="/images/interior-15.jpg" loading="lazy" alt="Quiet residential interior"/><figcaption>04 — FEELING</figcaption></motion.figure>
 <div className="intro-aside intro-aside-left">We begin with what matters most:<br/>the life happening inside the room.</div><div className="intro-aside intro-aside-right">In the balance of light, texture and proportion,<br/>a space becomes somewhere to belong.</div>
 <div className="intro-story-bottom"><span>SCROLL TO COMPOSE THE SPACE ↓</span><a href="#projects">EXPLORE OUR SPACES <ArrowUpRight size={17}/></a></div></div></section>
 <section id="projects" className="work section-pad"><div className="section-kicker"><span>02 / SELECTED SPACES</span><span>(04 PROJECT STUDIES)</span></div><div className="work-heading"><h2>Rooms to <em>remember.</em></h2><p>AN EXPLORATION OF MATERIAL,<br/>PROPORTION AND ATMOSPHERE.</p></div><div className="abv-projects">{projects.map((p,i)=><motion.button key={p.title} className={`abv-project ${i%2?'abv-project-reverse':''}`} onClick={()=>setDetail(i)} initial={prefersReduced?false:{opacity:0,y:55}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.8,ease}} aria-label={`Explore ${p.title}`}><span className="abv-project-photo"><img src={p.cover} alt={`${p.type} — ${p.title}`} loading="lazy"/><span className="abv-photo-counter">FORMA / {p.number}</span></span><span className="abv-project-info"><span className="abv-info-top">SELECTED PROJECT / {p.number} <span>{p.year}</span></span><span className="abv-info-middle"><span className="abv-project-category">{p.type}</span><strong>{p.title}</strong><span className="abv-project-rule"/><span className="abv-project-description">A study in atmosphere, proportion and the details that shape how a room is lived in.</span></span><span className="abv-info-bottom">VIEW PROJECT <ArrowUpRight size={21}/></span></span></motion.button>)}</div></section>
 <section className="manifesto"><div className="manifesto-img"/><div className="manifesto-overlay"/><div className="manifesto-content"><div className="section-kicker"><span>AN ONGOING STUDY</span><span>FORM / FUNCTION / FEELING</span></div><span className="manifesto-number">/ 003</span><h2>Not just<br/><em>a place.</em><br/>A feeling.</h2><p>Every detail changes the way a space is experienced.</p></div></section>
 <section id="approach" ref={approachRef} className="approach approach-cinema approach-pinned"><div className="approach-pin"><div className="approach-stage"><div className="section-kicker approach-kicker"><span>03 / OUR APPROACH</span><span>DESIGN IN MOTION — 01 / 04</span></div><div className="approach-cinema-head"><div><span className="approach-overline">THE PROCESS / AN ONGOING DIALOGUE</span><h2>DESIGN<br/><span>MEETS PURPOSE.</span></h2></div><p>We move from observation to atmosphere, shaping spaces that feel as thoughtful as they look.</p></div><div className="approach-controls"><span>EXPLORE THE PROCESS <ArrowRight size={14}/></span><div><button aria-label="Scroll process cards left" onClick={()=>approachTrack.current?.scrollBy({left:-360,behavior:prefersReduced?'auto':'smooth'})}><ArrowLeft size={20}/></button><button aria-label="Scroll process cards right" onClick={()=>approachTrack.current?.scrollBy({left:360,behavior:prefersReduced?'auto':'smooth'})}><ArrowRight size={20}/></button></div></div></div><div className="approach-scroll" ref={approachTrack} tabIndex={0} aria-label="Design process cards, scroll horizontally">{[{n:'01',title:'LISTEN & DISCOVER',body:'We begin with your routines, ambitions and the small details that make a room feel like yours.',icon:<Orbit size={70} strokeWidth={.75}/>},{n:'02',title:'IMAGINE & EXPLORE',body:'Spatial ideas take form through composition, light, materials and purposeful experimentation.',icon:<PanelsTopLeft size={70} strokeWidth={.75}/>},{n:'03',title:'SHAPE & DEVELOP',body:'Layouts, textures and layered elements evolve into a clear, considered design direction.',icon:<Layers3 size={70} strokeWidth={.75}/>},{n:'04',title:'REFINE & REALISE',body:'Proportion, craftsmanship and carefully resolved details bring the entire atmosphere together.',icon:<ScanLine size={70} strokeWidth={.75}/>}].map((step,i)=><motion.article className="approach-tile" key={step.n} initial={prefersReduced?false:{opacity:0,y:35}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.3}} transition={{duration:.65,delay:i*.08,ease}}><div className="approach-tile-top"><span>{step.n} / 04</span><span className="approach-line-icon" aria-hidden="true">{step.icon}</span></div><h3>{step.title}</h3><div className="approach-tile-bottom"><p>{step.body}</p><span>FORMA / DESIGN PROCESS <ArrowUpRight size={15}/></span></div></motion.article>)}</div><div className="approach-after"><span>THOUGHTFUL SPACES START WITH GOOD QUESTIONS.</span><span>SCROLL DOWN TO MOVE SIDEWAYS ↓</span></div></div></section>
 <section id="contact" className="contact section-pad">
 <div className="section-kicker"><span>04 / GET IN TOUCH</span><span>THE NEXT CHAPTER</span></div>
 <div className="contact-reveal"><motion.span className="contact-star" aria-hidden="true" initial={prefersReduced?false:{rotate:-75,opacity:0}} whileInView={{rotate:0,opacity:1}} viewport={{once:true}} transition={{duration:1.4,ease}}>✳</motion.span>
 <p className="contact-eyebrow">HAVE A SPACE IN MIND?</p><h2><motion.span className="contact-line" initial={prefersReduced?false:{y:'105%'}} whileInView={{y:0}} viewport={{once:true}} transition={{duration:.9,ease}}>Let's make room</motion.span><span className="contact-line"><motion.span initial={prefersReduced?false:{y:'105%'}} whileInView={{y:0}} viewport={{once:true}} transition={{duration:1,delay:.15,ease}}>for <em>something new.</em></motion.span></span></h2>
 <button className="contact-cta" onClick={()=>setEnquiryOpen(true)}>Begin your project <ArrowUpRight size={27}/></button><p className="contact-note">A conversation is where every good space begins.</p></div>
 <div className="footer"><span>FORMA<span className="wordmark-dot">.</span> <small>© {new Date().getFullYear()}</small></span><span>CONCEPT STUDIO · CONTACT DETAILS PENDING</span><a href="#home">BACK TO TOP ↑</a></div></section>
 <AnimatePresence>{enquiryOpen&&<motion.div className="enquiry-overlay" role="dialog" aria-modal="true" aria-label="Begin a project enquiry" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.3}}>
 <div className="enquiry-heading"><span>FORMA / NEW CONVERSATION</span><button type="button" onClick={()=>setEnquiryOpen(false)} aria-label="Close enquiry"><X size={22}/> CLOSE</button></div>
 <motion.div className="enquiry-content" initial={prefersReduced?false:{y:45,opacity:0}} animate={{y:0,opacity:1}} transition={{duration:.55,ease}}><span className="enquiry-label">01 / TELL US ABOUT YOUR SPACE</span><h2>Let's begin with<br/><em>your idea.</em></h2>
 <form className="enquiry-form" onSubmit={e=>{e.preventDefault();const subject=encodeURIComponent('FORMA concept project enquiry');const body=encodeURIComponent(['Project type: '+enquiry.type,'Location: '+enquiry.location,'Name: '+enquiry.name,'Email: '+enquiry.email,'Project details: '+enquiry.details].join('\n'));window.location.href='mailto:hello@example.com?subject='+subject+'&body='+body;}}>
 <label>WHAT ARE YOU PLANNING?<select value={enquiry.type} onChange={e=>setEnquiry(v=>({...v,type:e.target.value}))}><option>Residential interior</option><option>Commercial interior</option><option>Renovation</option><option>Something else</option></select></label>
 <label>PROJECT LOCATION<input required placeholder="City / area" value={enquiry.location} onChange={e=>setEnquiry(v=>({...v,location:e.target.value}))}/></label>
 <label>YOUR NAME<input required placeholder="How should we address you?" value={enquiry.name} onChange={e=>setEnquiry(v=>({...v,name:e.target.value}))}/></label>
 <label>EMAIL ADDRESS<input required type="email" placeholder="you@example.com" value={enquiry.email} onChange={e=>setEnquiry(v=>({...v,email:e.target.value}))}/></label>
 <label className="enquiry-full">A LITTLE ABOUT THE PROJECT<textarea rows={3} placeholder="Tell us about the space, timeline, or what you have in mind" value={enquiry.details} onChange={e=>setEnquiry(v=>({...v,details:e.target.value}))}/></label>
 <div className="enquiry-action"><p>This is a concept form. Submitting opens your email app with a prepared enquiry; it does not send information to a server. The recipient address is a placeholder.</p><button type="submit">Prepare enquiry email <ArrowUpRight size={21}/></button></div>
 </form></motion.div></motion.div>}</AnimatePresence>
 <AnimatePresence>{detail!==null&&<motion.div className="detail" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.3}} role="dialog" aria-modal="true" aria-label={projects[detail].title}><button className="detail-close" onClick={()=>setDetail(null)}><X size={22}/> CLOSE</button><div className="detail-hero" style={{backgroundImage:`linear-gradient(0deg,rgba(0,0,0,.5),rgba(0,0,0,.1)),url('${projects[detail].cover}')`}}><div><span>PROJECT STUDY / {projects[detail].number}</span><h2>{projects[detail].title}</h2><p>{projects[detail].type} · {projects[detail].year}</p></div></div><div className="detail-body"><div className="detail-note"><span>THE SPACE</span><p>A visual study of considered interiors, material, natural light and the details that create atmosphere.</p><small>Project names and descriptions are concept placeholders, pending studio confirmation.</small></div><div className="detail-gallery">{projects[detail].images.slice(1).map((img,i)=><img key={img} src={img} alt={`${projects[detail].title} interior detail ${i+1}`} loading="lazy"/>)}</div><div className="detail-end"><button onClick={()=>setDetail((detail+1)%projects.length)}>Next project <ArrowUpRight size={23}/></button><button onClick={()=>setDetail(null)}>Back to site <X size={19}/></button></div></div></motion.div>}</AnimatePresence>
 </main>}
